name: pimpmynurse
description: Helper app for our beloved nurses.
publish_to: 'none'
version: 0.2.0
homepage: https://github.com/fydrah/pimpmynurse
repository: https://github.com/fydrah/pimpmynurse
issue_tracker: https://github.com/fydrah/pimpmynurse/issues

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dropdown_search: ^5.0.6
  dropdown_selection: ^2.0.3
  english_words: ^4.0.0
  flex_color_scheme: ^7.0.0
  flutter:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  number_text_input_formatter: ^1.0.0+3
  package_info_plus: ^3.1.1
  provider: ^6.0.0
  scrollable_table_view: ^1.0.1
  shared_preferences: ^2.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  test: ^1.22.0

flutter:
  uses-material-design: true
  assets:
   - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  background_image: "assets/splash.png"

flutter_app_name:
  name: "PimpMyNurse"