name: Release

on:
  push:
    tags:        
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Prepare icons
        run: flutter pub run flutter_launcher_icons
      - name: Prepare splash screen
        run: flutter pub run flutter_native_splash:create
      - name: Prepare upload signing
        env:
          JKS_B64:  ${{ secrets.JKS_B64 }}
          JKS_STORE_FILE: upload-keystore.jks
        run: base64 -d <<< $JKS_B64 > ./android/app/$JKS_STORE_FILE
      - name: Build APK
        env:
          JKS_KEY_ALIAS: upload
          JKS_KEY_PASSWORD: ${{ secrets.JKS_KEY_PASSWORD }}
          JKS_STORE_FILE: upload-keystore.jks
          JKS_STORE_PASSWORD: ${{ secrets.JKS_STORE_PASSWORD }}
        run: flutter build bundle
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelogs/${{ github.ref }}
          files: build/app/outputs/release/*
          make_latest: true